"""Model gateway contracts for AlphaBrief."""

from alphabrief_models.adapters import OllamaProviderAdapter
from alphabrief_models.briefs import (
    BriefHorizon,
    DailyAlphaBrief,
    MarketBrief,
    MarketRegime,
    SymbolBrief,
    SymbolDirection,
    SymbolVerdict,
)
from alphabrief_models.daily import (
    DailyBriefGenerationErrorCode,
    DailyBriefGenerationResult,
    generate_daily_alpha_brief,
)
from alphabrief_models.evaluation import (
    MAX_SAMPLE_COUNT,
    EvalDataset,
    EvalDatasetSpec,
    EvalResult,
    EvalSample,
    ModelEvaluation,
    ModelEvaluator,
    eval_result_to_record,
)
from alphabrief_models.evaluation_datasets import (
    BUNDLED_DATASET_SPECS,
    BUNDLED_DATASETS,
    DAILY_BRIEF_V1_SPEC,
    DEBATE_RESPONSE_V1_SPEC,
    KNOWLEDGE_V1_SPEC,
    MARKET_SUMMARY_V1_SPEC,
    get_dataset_by_id,
)
from alphabrief_models.gateway import (
    FakeProviderAdapter,
    ModelCallBudget,
    ModelCallClassification,
    ModelCallRecord,
    ModelCallStatus,
    ModelCapability,
    ModelGateway,
    ModelGatewayResult,
    ModelProviderError,
    ModelRequest,
    ModelResponse,
    ModelResponseStatus,
    ModelTaskType,
    ProviderAdapter,
    classify_provider_error,
)
from alphabrief_models.kronos import (
    DeterministicKronosRuntime,
    KronosDirectionBias,
    KronosForecastAdapter,
    KronosForecastEvidence,
    KronosForecastPoint,
    KronosForecastReport,
    KronosForecastRequest,
    KronosRuntime,
    PredictorKronosRuntime,
    UnavailableKronosRuntime,
    build_kronos_evidence,
    build_kronos_model_request,
    forecast_with_kronos_gateway,
)
from alphabrief_models.openai_adapter import OpenAIProviderAdapter
from alphabrief_models.prompts import (
    PHASE11_PROMPT_TEMPLATES,
    PromptTemplate,
    PromptTemplateError,
    PromptTemplateRegistry,
    RenderedPrompt,
    build_default_prompt_registry,
    render_brief_prompt_v2,
)
from alphabrief_models.quality_gate import (
    MetricGateResult,
    QualityMetrics,
    QualityThresholds,
    evaluate_quality_gate,
)
from alphabrief_models.registry import ModelProfile, ModelRegistry, ProviderConfig
from alphabrief_models.repair import (
    RepairVerdict,
    StructuredRepairResult,
    default_repair_prompt_builder,
    repair_structured_output,
)
from alphabrief_models.router import (
    MIN_JSON_VALID_RATE,
    MIN_SCHEMA_PASS_RATE,
    ModelRouteDecision,
    ModelRouter,
    PerformanceSnapshot,
)
from alphabrief_models.structured_output import (
    StructuredOutputErrorCode,
    StructuredOutputResult,
    parse_structured_output,
)

__all__ = [
    "BUNDLED_DATASETS",
    "BUNDLED_DATASET_SPECS",
    "BriefHorizon",
    "DAILY_BRIEF_V1_SPEC",
    "DEBATE_RESPONSE_V1_SPEC",
    "DailyAlphaBrief",
    "DailyBriefGenerationErrorCode",
    "DailyBriefGenerationResult",
    "EvalDataset",
    "EvalDatasetSpec",
    "EvalResult",
    "EvalSample",
    "FakeProviderAdapter",
    "DeterministicKronosRuntime",
    "KNOWLEDGE_V1_SPEC",
    "KronosDirectionBias",
    "KronosForecastAdapter",
    "KronosForecastEvidence",
    "KronosForecastPoint",
    "KronosForecastReport",
    "KronosForecastRequest",
    "KronosRuntime",
    "MARKET_SUMMARY_V1_SPEC",
    "MAX_SAMPLE_COUNT",
    "MarketBrief",
    "MarketRegime",
    "MIN_JSON_VALID_RATE",
    "MIN_SCHEMA_PASS_RATE",
    "ModelCallBudget",
    "ModelCallClassification",
    "ModelCallRecord",
    "ModelCallStatus",
    "ModelCapability",
    "ModelEvaluation",
    "ModelEvaluator",
    "ModelGateway",
    "ModelGatewayResult",
    "ModelProviderError",
    "ModelProfile",
    "ModelRequest",
    "ModelResponse",
    "ModelResponseStatus",
    "ModelRegistry",
    "ModelRouteDecision",
    "ModelRouter",
    "ModelTaskType",
    "OllamaProviderAdapter",
    "OpenAIProviderAdapter",
    "PerformanceSnapshot",
    "PHASE11_PROMPT_TEMPLATES",
    "PredictorKronosRuntime",
    "ProviderAdapter",
    "ProviderConfig",
    "PromptTemplate",
    "PromptTemplateError",
    "PromptTemplateRegistry",
    "QualityMetrics",
    "QualityThresholds",
    "MetricGateResult",
    "RenderedPrompt",
    "RepairVerdict",
    "StructuredOutputErrorCode",
    "StructuredRepairResult",
    "StructuredOutputResult",
    "SymbolBrief",
    "SymbolDirection",
    "SymbolVerdict",
    "UnavailableKronosRuntime",
    "build_default_prompt_registry",
    "build_kronos_evidence",
    "build_kronos_model_request",
    "default_repair_prompt_builder",
    "classify_provider_error",
    "eval_result_to_record",
    "evaluate_quality_gate",
    "forecast_with_kronos_gateway",
    "generate_daily_alpha_brief",
    "get_dataset_by_id",
    "parse_structured_output",
    "render_brief_prompt_v2",
    "repair_structured_output",
]
