"""Strategy specification schemas for AlphaBrief."""

from alphabrief_strategy.builtins import MovingAverageTrendStrategy
from alphabrief_strategy.dsl import (
    DATA_ALLOWLIST,
    INDICATOR_ALLOWLIST,
    ComparisonNode,
    DataNode,
    DslCompileError,
    DslEvaluationError,
    EvaluationContext,
    IndicatorNode,
    LiteralNode,
    LogicNode,
    NotNode,
    StrategyCondition,
    compile_condition,
    evaluate_condition,
)
from alphabrief_strategy.interface import (
    StrategyExecutionError,
    StrategyInput,
    StrategyOutput,
    StrategyProtocol,
    run_strategy,
)
from alphabrief_strategy.spec import (
    EvaluationPeriod,
    ExternalEvidenceConfig,
    StrategyCosts,
    StrategyEvaluation,
    StrategyRisk,
    StrategyRule,
    StrategySpec,
    StrategyUniverse,
)

__all__ = [
    "DATA_ALLOWLIST",
    "INDICATOR_ALLOWLIST",
    "ComparisonNode",
    "DataNode",
    "DslCompileError",
    "DslEvaluationError",
    "EvaluationContext",
    "EvaluationPeriod",
    "ExternalEvidenceConfig",
    "IndicatorNode",
    "LiteralNode",
    "LogicNode",
    "MovingAverageTrendStrategy",
    "NotNode",
    "StrategyCondition",
    "StrategyExecutionError",
    "StrategyInput",
    "StrategyOutput",
    "StrategyProtocol",
    "StrategyCosts",
    "StrategyEvaluation",
    "StrategyRisk",
    "StrategyRule",
    "StrategySpec",
    "StrategyUniverse",
    "compile_condition",
    "evaluate_condition",
    "run_strategy",
]
